const PDFDocument = require('pdfkit');

const BRAND = '#1a56db';
const DARK = '#111827';
const GRAY = '#6b7280';
const LIGHT = '#f3f4f6';
const SUCCESS = '#059669';

function header(doc, title) {
  doc.rect(0, 0, doc.page.width, 80).fill(BRAND);
  doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold').text('BIZFLOW', 40, 25);
  doc.fontSize(10).font('Helvetica').text('Inventory & GST Billing System', 40, 52);
  doc.fillColor('#ffffff').fontSize(14).font('Helvetica-Bold').text(title, 0, 30, { align: 'right', width: doc.page.width - 40 });
  doc.moveDown(3);
}

function footer(doc) {
  const bottom = doc.page.height - 50;
  doc.moveTo(40, bottom).lineTo(doc.page.width - 40, bottom).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
  doc.fillColor(GRAY).fontSize(9).font('Helvetica')
    .text('Generated by Bizflow', 40, bottom + 10)
    .text(new Date().toLocaleString('en-IN'), 0, bottom + 10, { align: 'right', width: doc.page.width - 40 });
}

function rupee(n) {
  return '₹' + parseFloat(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

exports.generateInvoice = (data, stream) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  doc.pipe(stream);

  // Header
  doc.rect(0, 0, doc.page.width, 80).fill(BRAND);
  doc.fillColor('#fff').fontSize(22).font('Helvetica-Bold').text('BIZFLOW', 40, 22);
  doc.fontSize(9).font('Helvetica').text('Inventory & GST Billing System', 40, 50);
  doc.fontSize(18).font('Helvetica-Bold').text('TAX INVOICE', 0, 28, { align: 'right', width: doc.page.width - 40 });
  doc.fontSize(10).font('Helvetica').text(data.invoice_no, 0, 52, { align: 'right', width: doc.page.width - 40 });

  doc.y = 100;

  // Invoice meta
  doc.rect(40, 100, doc.page.width - 80, 60).fill(LIGHT);
  doc.fillColor(DARK).fontSize(9).font('Helvetica');
  const dateStr = new Date(data.created_at).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  doc.text(`Date: ${dateStr}`, 55, 112);
  doc.text(`Invoice No: ${data.invoice_no}`, 55, 128);
  doc.text(`Payment: ${(data.payment_method || 'cash').toUpperCase()}`, 55, 144);
  doc.text(`Status: ${(data.status || 'unpaid').toUpperCase()}`, 200, 112);

  // Party info
  if (data.party_name) {
    doc.fontSize(9).font('Helvetica-Bold').fillColor(GRAY).text('BILLED TO', 350, 112);
    doc.font('Helvetica').fillColor(DARK).fontSize(10).text(data.party_name, 350, 126);
    if (data.party_phone) doc.fontSize(9).text(`Ph: ${data.party_phone}`, 350, 141);
    if (data.party_gstin) doc.fontSize(9).text(`GSTIN: ${data.party_gstin}`, 350, 155);
  }

  doc.y = 175;

  // Items table header
  doc.rect(40, 180, doc.page.width - 80, 22).fill(BRAND);
  doc.fillColor('#fff').fontSize(9).font('Helvetica-Bold');
  doc.text('#', 50, 188, { width: 20 });
  doc.text('Product', 74, 188, { width: 200 });
  doc.text('Rate', 280, 188, { width: 70, align: 'right' });
  doc.text('Qty', 355, 188, { width: 40, align: 'right' });
  doc.text('Unit', 400, 188, { width: 40 });
  doc.text('Amount', 445, 188, { width: 100, align: 'right' });

  let y = 205;
  (data.items || []).forEach((item, i) => {
    if (i % 2 === 0) doc.rect(40, y - 3, doc.page.width - 80, 18).fill('#f9fafb');
    doc.fillColor(DARK).fontSize(9).font('Helvetica');
    doc.text(String(i + 1), 50, y, { width: 20 });
    doc.text(item.product_name, 74, y, { width: 200 });
    doc.text(rupee(item.rate), 280, y, { width: 70, align: 'right' });
    doc.text(String(item.quantity), 355, y, { width: 40, align: 'right' });
    doc.text(item.unit || 'pcs', 400, y, { width: 40 });
    doc.text(rupee(item.line_total), 445, y, { width: 100, align: 'right' });
    y += 18;
  });

  // Totals
  y += 10;
  doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
  y += 10;

  const totalsX = 350;
  const valueX = doc.page.width - 40;
  function totRow(label, value, bold = false) {
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9).fillColor(bold ? DARK : GRAY);
    doc.text(label, totalsX, y, { width: 110 });
    doc.text(value, totalsX + 110, y, { width: valueX - totalsX - 110, align: 'right' });
    y += 16;
  }
  totRow('Subtotal', rupee(data.subtotal));
  totRow(`CGST (${data.cgst_rate}%)`, rupee(data.cgst_amount));
  totRow(`SGST (${data.sgst_rate}%)`, rupee(data.sgst_amount));
  y += 4;
  doc.rect(totalsX, y - 4, valueX - totalsX, 22).fill(BRAND);
  doc.fillColor('#fff').fontSize(11).font('Helvetica-Bold');
  doc.text('TOTAL', totalsX + 4, y + 2, { width: 110 });
  doc.text(rupee(data.total), totalsX + 110, y + 2, { width: valueX - totalsX - 115, align: 'right' });

  footer(doc);
  doc.end();
};

exports.generateStockReport = (products, stream) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  doc.pipe(stream);
  header(doc, 'STOCK REPORT');

  const dateStr = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  doc.fillColor(GRAY).fontSize(10).text(`As of: ${dateStr}`, 40, doc.y);
  doc.moveDown(0.5);

  // Table header
  let y = doc.y + 5;
  doc.rect(40, y, doc.page.width - 80, 22).fill(BRAND);
  doc.fillColor('#fff').fontSize(9).font('Helvetica-Bold');
  doc.text('Product Name', 50, y + 7, { width: 200 });
  doc.text('Category', 255, y + 7, { width: 100 });
  doc.text('Price', 360, y + 7, { width: 80, align: 'right' });
  doc.text('Qty', 445, y + 7, { width: 40, align: 'right' });
  doc.text('Unit', 490, y + 7, { width: 55 });

  y += 25;
  let totalProducts = 0, lowStock = 0;

  products.forEach((p, i) => {
    if (i % 2 === 0) doc.rect(40, y - 2, doc.page.width - 80, 17).fill('#f9fafb');
    const isLow = p.quantity <= 5;
    doc.fillColor(isLow ? '#dc2626' : DARK).fontSize(9).font('Helvetica');
    doc.text(p.name, 50, y + 2, { width: 200 });
    doc.fillColor(DARK).text(p.category, 255, y + 2, { width: 100 });
    doc.text(rupee(p.price), 360, y + 2, { width: 80, align: 'right' });
    doc.fillColor(isLow ? '#dc2626' : DARK).font(isLow ? 'Helvetica-Bold' : 'Helvetica');
    doc.text(String(p.quantity), 445, y + 2, { width: 40, align: 'right' });
    doc.fillColor(DARK).font('Helvetica').text(p.unit || 'pcs', 490, y + 2, { width: 55 });
    y += 17;
    totalProducts++;
    if (isLow) lowStock++;
  });

  y += 15;
  doc.moveTo(40, y).lineTo(doc.page.width - 40, y).strokeColor('#e5e7eb').lineWidth(0.5).stroke();
  y += 10;
  doc.fillColor(DARK).fontSize(10).font('Helvetica-Bold').text(`Total Products: ${totalProducts}`, 40, y);
  doc.fillColor('#dc2626').text(`Low Stock (≤5): ${lowStock}`, 200, y);

  footer(doc);
  doc.end();
};

exports.generateSalesReport = ({ invoices, summary, month, year }, stream) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  doc.pipe(stream);
  const monthName = new Date(year, month - 1).toLocaleString('en-IN', { month: 'long', year: 'numeric' });
  header(doc, 'MONTHLY SALES REPORT');

  doc.fillColor(GRAY).fontSize(10).text(`Period: ${monthName}`, 40, doc.y);
  doc.moveDown(0.5);

  // Summary cards
  let cy = doc.y + 5;
  const cardW = 115, cardH = 50, gap = 12, startX = 40;
  const cards = [
    { label: 'Invoices', value: String(invoices.length) },
    { label: 'Subtotal', value: rupee(summary.subtotal) },
    { label: 'CGST', value: rupee(summary.cgst) },
    { label: 'SGST', value: rupee(summary.sgst) },
    { label: 'Total', value: rupee(summary.total) },
  ];
  cards.forEach((c, i) => {
    const cx = startX + i * (cardW + gap);
    doc.rect(cx, cy, cardW, cardH).fill(i === 4 ? BRAND : LIGHT);
    doc.fillColor(i === 4 ? '#fff' : GRAY).fontSize(8).font('Helvetica').text(c.label, cx + 8, cy + 8, { width: cardW - 16 });
    doc.fillColor(i === 4 ? '#fff' : DARK).fontSize(11).font('Helvetica-Bold').text(c.value, cx + 8, cy + 22, { width: cardW - 16 });
  });

  let y = cy + cardH + 20;
  doc.rect(40, y, doc.page.width - 80, 22).fill(BRAND);
  doc.fillColor('#fff').fontSize(9).font('Helvetica-Bold');
  doc.text('Invoice No', 50, y + 7, { width: 100 });
  doc.text('Party', 155, y + 7, { width: 130 });
  doc.text('Date', 290, y + 7, { width: 80 });
  doc.text('Method', 375, y + 7, { width: 60 });
  doc.text('Status', 440, y + 7, { width: 55 });
  doc.text('Total', 500, y + 7, { width: 55, align: 'right' });

  y += 25;
  invoices.forEach((inv, i) => {
    if (i % 2 === 0) doc.rect(40, y - 2, doc.page.width - 80, 17).fill('#f9fafb');
    const statusColor = inv.status === 'paid' ? SUCCESS : inv.status === 'partial' ? '#d97706' : '#dc2626';
    doc.fillColor(DARK).fontSize(8).font('Helvetica');
    doc.text(inv.invoice_no, 50, y + 2, { width: 100 });
    doc.text(inv.party_name || 'Walk-in', 155, y + 2, { width: 130 });
    doc.text(new Date(inv.created_at).toLocaleDateString('en-IN'), 290, y + 2, { width: 80 });
    doc.text((inv.payment_method || '').toUpperCase(), 375, y + 2, { width: 60 });
    doc.fillColor(statusColor).text((inv.status || '').toUpperCase(), 440, y + 2, { width: 55 });
    doc.fillColor(DARK).font('Helvetica-Bold').text(rupee(inv.total), 500, y + 2, { width: 55, align: 'right' });
    y += 17;
  });

  footer(doc);
  doc.end();
};
